# Generated by Django 3.1.13 on 2021-09-19 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210828_0224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectBeautyVenue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_connect', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_connect_beauty_venue',
            },
        ),
    ]
