# Generated by Django 3.1.13 on 2021-09-19 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_connectbeautyvenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectbeautyvenue',
            name='is_connect',
            field=models.BooleanField(default=False),
        ),
    ]
