# Generated by Django 3.1.13 on 2021-08-28 04:29

from django.db import migrations
import unicollege.courses.fields


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_content_file_image_text_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=unicollege.courses.fields.OrderField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=unicollege.courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
